{{- $fn := include "nexwall.fullname" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fn }}-db
  labels:
    {{- include "nexwall.labels" . | nindent 4 }}
    component: db
spec:
  serviceName: {{ $fn }}-db
  replicas: 1
  selector:
    matchLabels:
      component: db
      tenant-id: "{{ .Values.tenantId }}"
  template:
    metadata:
      labels:
        {{- include "nexwall.labels" . | nindent 8 }}
        component: db
    spec:
      containers:
        - name: db
          image: {{ .Values.monitoringImages.timescaledb }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ $fn }}-db
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.resources.db | nindent 12 }}
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "report"]
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.storage.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.storage.dbSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fn }}-db
  labels:
    {{- include "nexwall.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    component: db
    tenant-id: "{{ .Values.tenantId }}"
  ports:
    - port: 5432
